#!/usr/bin/env python3
"""
run_all.py — One-command reproduction of the full Voynich analysis pipeline.

Runs (in order):
  1. scripts/00_validate_datasets.py   — verify bundled data checksums
  2. scripts/01_core_analysis.py       — transition rules, AIIN invariance, SC
  3. scripts/02_cross_linguistic.py    — 11-language comparison
  4. scripts/03_stress_tests.py        — robustness checks

Results are written to results/ as six canonical JSON files (one of which,
prefix_suffix_analysis.json, is precomputed and not regenerated by these
scripts — it reflects a manual, one-off analysis pass).

Usage:
  python run_all.py                  # run everything in order, fail fast
  python run_all.py --skip-validate  # skip the initial dataset validation
  python run_all.py --tests          # after pipeline, run canonical-value tests
  python run_all.py --dry-run        # print what would run, don't execute

Exit codes:
  0 — all steps succeeded
  1 — a step failed (stderr and the failed script's output are shown)
  2 — invalid arguments or missing dependencies
"""

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
RESULTS_DIR = PROJECT_ROOT / "results"
TESTS_DIR = PROJECT_ROOT / "tests"

PIPELINE = [
    ("Validate frozen datasets", SCRIPTS_DIR / "00_validate_datasets.py", None),
    ("Core analysis",            SCRIPTS_DIR / "01_core_analysis.py",    RESULTS_DIR / "core_analysis_results.json"),
    ("Cross-linguistic",         SCRIPTS_DIR / "02_cross_linguistic.py", RESULTS_DIR / "cross_linguistic_results.json"),
    ("Stress tests",             SCRIPTS_DIR / "03_stress_tests.py",     RESULTS_DIR / "stress_test_results.json"),
]

BANNER = "=" * 72


def log(msg: str) -> None:
    """Print with flush so output appears in real time under CI."""
    print(msg, flush=True)


def check_python_deps() -> bool:
    """Verify required packages import. Returns True if all present."""
    missing = []
    for pkg in ("numpy", "pandas", "scipy", "pyarrow"):
        try:
            __import__(pkg)
        except ImportError:
            missing.append(pkg)
    if missing:
        log(f"ERROR: missing Python packages: {', '.join(missing)}")
        log("Install with: pip install -r requirements.txt")
        return False
    return True


def run_step(label: str, script: Path, expected_output: Path, dry_run: bool) -> bool:
    """Run one pipeline step. Returns True on success."""
    log("")
    log(BANNER)
    log(f"STEP: {label}")
    log(f"  script: {script.relative_to(PROJECT_ROOT)}")
    if expected_output:
        log(f"  output: {expected_output.relative_to(PROJECT_ROOT)}")
    log(BANNER)

    if not script.exists():
        log(f"ERROR: script not found: {script}")
        return False

    if dry_run:
        log("(dry-run: skipping execution)")
        return True

    start = time.time()
    # Run in project root so relative paths in scripts work
    result = subprocess.run(
        [sys.executable, str(script)],
        cwd=str(PROJECT_ROOT),
    )
    elapsed = time.time() - start

    if result.returncode != 0:
        log(f"FAILED after {elapsed:.1f}s (exit code {result.returncode})")
        return False

    log(f"OK ({elapsed:.1f}s)")

    # Sanity check: did the expected output file get written?
    if expected_output and not expected_output.exists():
        log(f"WARNING: expected output not found: {expected_output}")
        log("  Script reported success but produced no output file.")
        return False

    return True


def run_tests() -> bool:
    """Run the canonical-value tests after the pipeline completes."""
    log("")
    log(BANNER)
    log("STEP: Canonical value tests")
    log(BANNER)

    test_file = TESTS_DIR / "test_canonical_values.py"
    if not test_file.exists():
        log(f"ERROR: test file not found: {test_file}")
        return False

    # Prefer pytest if available; fall back to running as a script
    try:
        import pytest  # noqa: F401
        cmd = [sys.executable, "-m", "pytest", str(test_file), "-v"]
    except ImportError:
        cmd = [sys.executable, str(test_file)]

    result = subprocess.run(cmd, cwd=str(PROJECT_ROOT))
    if result.returncode != 0:
        log(f"TESTS FAILED (exit code {result.returncode})")
        return False

    log("TESTS PASSED")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Reproduce the full Voynich analysis pipeline.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--skip-validate", action="store_true",
                        help="Skip the initial dataset validation step")
    parser.add_argument("--tests", action="store_true",
                        help="After pipeline, run tests/test_canonical_values.py")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would run without executing")
    args = parser.parse_args()

    log(BANNER)
    log("VOYNICH TRANSITION GRAMMAR — FULL PIPELINE")
    log(BANNER)
    log(f"Project root: {PROJECT_ROOT}")
    log(f"Python:       {sys.version.split()[0]}")
    log(f"Executable:   {sys.executable}")

    if not args.dry_run and not check_python_deps():
        return 2

    RESULTS_DIR.mkdir(exist_ok=True)

    overall_start = time.time()
    steps_to_run = PIPELINE
    if args.skip_validate:
        steps_to_run = [s for s in PIPELINE if "validate" not in s[0].lower()]

    for label, script, expected in steps_to_run:
        if not run_step(label, script, expected, args.dry_run):
            log("")
            log(BANNER)
            log("PIPELINE FAILED")
            log(BANNER)
            return 1

    if args.tests and not args.dry_run:
        if not run_tests():
            log("")
            log(BANNER)
            log("PIPELINE OK but TESTS FAILED")
            log(BANNER)
            return 1

    total = time.time() - overall_start
    log("")
    log(BANNER)
    log(f"PIPELINE COMPLETE in {total:.1f}s")
    log(BANNER)
    log("")
    log("Results written to:")
    for f in sorted(RESULTS_DIR.glob("*.json")):
        size_kb = f.stat().st_size / 1024
        log(f"  {f.relative_to(PROJECT_ROOT)}  ({size_kb:.1f} KB)")
    txt = RESULTS_DIR / "validation_report.txt"
    if txt.exists():
        size_kb = txt.stat().st_size / 1024
        log(f"  {txt.relative_to(PROJECT_ROOT)}  ({size_kb:.1f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
