#!/usr/bin/env python3
"""
06_paradigm_null.py — Null-model test for the productive-paradigm claim (Finding 1.8).

CONTEXT
-------
Finding 1.8 (durable_findings.md §1.8; paper §3.9) reports that log-frequency vs
edit-distance-1 variant count has correlation r = 0.42–0.71 for Voynich families
(QOK r=0.42, CHEDY r=0.59, AIIN r=0.71). The paper argues this is evidence of
productive morphology, "a standard property of natural-language morphology."

OBJECTION (independent audit, §3.5)
-----------------------------------
This correlation is near-automatic for any Zipfian distribution on a Levenshtein
edit graph. High-frequency strings have more edit-1 neighbors by combinatorics
alone: a common string has more chances for any given single-character mutation
to land on another attested string. Before the correlation can be cited as
evidence for morphology, it must be shown that Voynich's r *exceeds* what a
null model without morphology produces.

WHAT THIS SCRIPT DOES
---------------------
For each family (QOK, CHEDY, AIIN) we compute r three ways:

1. REAL: on the actual Voynich tokens (reproduces the published values).
2. TRIGRAM NULL: a null corpus generated by a character trigram model fit to
   Voynich characters. Matches character unigram and bigram statistics of the
   real corpus but contains no morphological structure. The corpus is the same
   size as the Voynich corpus.
3. NATURAL LANGUAGE COMPARISON: r for frequency vs edit-1 variants in Chaucer
   tokens (Middle English, Gutenberg #22120). Chaucer has known productive
   morphology in a medieval corpus of comparable scale.

INTERPRETATION RULES (declared BEFORE seeing results)
-----------------------------------------------------
- If Voynich r >> Trigram-null r AND Voynich r ≈ Chaucer r:
  The finding supports productive morphology. "Productive paradigm" language
  is justified.

- If Voynich r ≈ Trigram-null r (i.e., within a factor of ~1.3):
  The correlation is explained by Zipfian combinatorics alone. The
  "productive morphology" interpretation is not supported. Language must be
  narrowed to "edit-distance graph structure consistent with a Zipfian
  distribution, not distinguishable from a character-trigram null."

- If Voynich r is noticeably above null but below Chaucer:
  Partial support. Language must be narrowed to "above combinatorial baseline
  but weaker than natural-language morphology."

We run 10 trigram null replicates per family to get a null distribution,
not just a point estimate.

Usage:
  python scripts/06_paradigm_null.py

Output:
  results/paradigm_null_results.json
"""

import os
import sys
import json
import re
import random
from collections import Counter, defaultdict
from math import log
import numpy as np

random.seed(42)
np.random.seed(42)

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

# ─── Loaders ─────────────────────────────────────────────────────────────────

def load_voynich_tokens():
    import pandas as pd
    path = os.path.join(PROJECT_ROOT, "data", "raw", "voynich",
                        "AncientLanguages_Voynich_snapshot", "train.parquet")
    df = pd.read_parquet(path)
    zl = df[df["source_name"] == "Zandbergen-Landini"].copy()
    tokens = []
    for text in zl["text"].dropna():
        for line in str(text).split("\n"):
            line = line.strip()
            if not line:
                continue
            for tok in line.split():
                tok = re.sub(r"[^a-z]", "", tok.lower())
                if tok:
                    tokens.append(tok)
    return tokens


def load_chaucer_tokens():
    path = os.path.join(PROJECT_ROOT, "data", "raw", "cross_linguistic",
                        "middle_english", "chaucer_canterbury_tales_22120.txt")
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8", errors="ignore") as f:
        text = f.read().lower()
    tokens = re.findall(r"[a-z]+", text)
    return tokens


# ─── Family classification (matches the rest of the project) ────────────────

def classify(tok):
    if tok.startswith("qok"):
        return "QOK"
    if tok.startswith("ok"):
        return "OK"
    if tok.startswith("ot"):
        return "OT"
    if any(s in tok for s in ("chedy", "shedy", "chey", "shey")):
        return "CHEDY"
    if "aiin" in tok or "ain" in tok:
        return "AIIN"
    return "OTHER"


# ─── Edit distance 1 neighbors within a vocabulary ──────────────────────────

def edit1_neighbors(target, vocab_set):
    """Count tokens in vocab_set that are exactly edit-distance 1 from target.
    Operations: substitute, insert, delete a single character.
    """
    neighbors = set()
    chars = "abcdefghijklmnopqrstuvwxyz"
    # substitutions
    for i in range(len(target)):
        for c in chars:
            if c == target[i]:
                continue
            candidate = target[:i] + c + target[i+1:]
            if candidate in vocab_set and candidate != target:
                neighbors.add(candidate)
    # insertions
    for i in range(len(target) + 1):
        for c in chars:
            candidate = target[:i] + c + target[i:]
            if candidate in vocab_set and candidate != target:
                neighbors.add(candidate)
    # deletions
    for i in range(len(target)):
        candidate = target[:i] + target[i+1:]
        if candidate in vocab_set and candidate != target:
            neighbors.add(candidate)
    return len(neighbors)


def compute_freq_variant_correlation(tokens, family_filter=None, top_n=50):
    """Return Pearson r between log-frequency and edit-1 variant count.

    Matches the definition in scripts/04_extended_analysis.py:
    - take the top_n most frequent members of the family (or all tokens if
      family_filter is None)
    - compute edit-1 neighbor count within that family's vocabulary
    - correlate log(frequency) with neighbor count.
    """
    counts = Counter(tokens)
    if family_filter is not None:
        vocab = {t: c for t, c in counts.items() if family_filter(t)}
    else:
        vocab = dict(counts)
    top = sorted(vocab.items(), key=lambda kv: -kv[1])[:top_n]
    vocab_set = set(t for t, _ in top)
    log_freqs = []
    variant_counts = []
    for tok, freq in top:
        log_freqs.append(log(freq))
        variant_counts.append(edit1_neighbors(tok, vocab_set))
    if len(log_freqs) < 5:
        return None, len(log_freqs)
    r = float(np.corrcoef(log_freqs, variant_counts)[0, 1])
    return r, len(log_freqs)


# ─── Trigram generator ───────────────────────────────────────────────────────

def fit_char_trigram(tokens):
    """Fit a character trigram model with start/end symbols."""
    START = "\x02"
    END = "\x03"
    trigrams = defaultdict(Counter)
    for tok in tokens:
        padded = START + START + tok + END
        for i in range(len(padded) - 2):
            context = padded[i:i+2]
            nxt = padded[i+2]
            trigrams[context][nxt] += 1
    return trigrams


def generate_trigram_token(trigrams, max_len=20):
    START = "\x02"
    END = "\x03"
    context = START + START
    out = []
    for _ in range(max_len):
        if context not in trigrams:
            break
        counter = trigrams[context]
        total = sum(counter.values())
        r = random.random() * total
        cum = 0
        for c, n in counter.items():
            cum += n
            if r < cum:
                nxt = c
                break
        if nxt == END:
            break
        out.append(nxt)
        context = context[1] + nxt
    return "".join(out)


def generate_trigram_corpus(tokens, n_tokens):
    trigrams = fit_char_trigram(tokens)
    out = []
    while len(out) < n_tokens:
        t = generate_trigram_token(trigrams)
        if t:
            out.append(t)
    return out


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    print("Loading Voynich tokens...")
    voy = load_voynich_tokens()
    print(f"  {len(voy)} Voynich tokens")

    print("Loading Chaucer tokens...")
    chaucer = load_chaucer_tokens()
    if chaucer is None:
        print("  WARNING: Chaucer corpus not found; skipping NL comparison")
    else:
        print(f"  {len(chaucer)} Chaucer tokens")

    families = {
        "QOK": lambda t: t.startswith("qok"),
        "CHEDY": lambda t: any(s in t for s in ("chedy", "shedy", "chey", "shey")),
        "AIIN": lambda t: ("aiin" in t) or ("ain" in t),
    }

    results = {
        "description": (
            "Null-model test for the productive-paradigm claim (Finding 1.8). "
            "Tests whether the log-frequency vs edit-1 variant count correlation "
            "exceeds a character-trigram null that lacks morphological structure."
        ),
        "methodology": {
            "voynich_real": "Top 50 members of each family by frequency; Pearson r of log-freq vs edit-1 neighbor count within that family's top-50.",
            "trigram_null": "10 replicates: fit character trigram model on real Voynich; generate synthetic corpus of same size; classify with same family rules; compute same correlation.",
            "chaucer_natural": "All tokens from Chaucer's Canterbury Tales; top 50 by frequency; same correlation definition. Uses ALL tokens, not family-filtered, since the EVA family definitions don't apply.",
        },
        "interpretation_rules": {
            "supports_productive_morphology": "Voynich r >> trigram null r AND Voynich r ≈ Chaucer r",
            "artifact_only": "Voynich r ≈ trigram null r (within factor 1.3)",
            "partial_support": "Voynich r above null but below NL"
        },
        "results": {}
    }

    # --- Voynich real ---
    print("\n=== VOYNICH REAL ===")
    voy_real = {}
    for fam_name, fam_filter in families.items():
        r, n = compute_freq_variant_correlation(voy, fam_filter, top_n=50)
        voy_real[fam_name] = {"r": round(r, 3) if r is not None else None, "n_types": n}
        print(f"  {fam_name}: r={r:.3f}, n={n}")

    # --- Trigram null: family-filtered ---
    print("\n=== TRIGRAM NULL (10 replicates per family) ===")
    n_replicates = 10
    null_results = {fam: [] for fam in families}
    for rep in range(n_replicates):
        random.seed(100 + rep)
        np.random.seed(100 + rep)
        synthetic = generate_trigram_corpus(voy, len(voy))
        for fam_name, fam_filter in families.items():
            r, n = compute_freq_variant_correlation(synthetic, fam_filter, top_n=50)
            if r is not None:
                null_results[fam_name].append(r)
        print(f"  replicate {rep+1}/{n_replicates} done")

    null_summary = {}
    for fam_name in families:
        rs = null_results[fam_name]
        if rs:
            null_summary[fam_name] = {
                "n_replicates": len(rs),
                "mean": round(float(np.mean(rs)), 3),
                "sd": round(float(np.std(rs)), 3),
                "min": round(min(rs), 3),
                "max": round(max(rs), 3),
                "p95": round(float(np.percentile(rs, 95)), 3),
            }
        else:
            null_summary[fam_name] = None

    print("\nNull summary:")
    for fam, s in null_summary.items():
        if s:
            print(f"  {fam}: mean={s['mean']}, sd={s['sd']}, 95th pct={s['p95']}")

    # --- Chaucer natural-language reference ---
    chaucer_r = None
    if chaucer is not None:
        print("\n=== CHAUCER (natural-language reference) ===")
        r, n = compute_freq_variant_correlation(chaucer, family_filter=None, top_n=50)
        chaucer_r = {"r": round(r, 3) if r is not None else None, "n_types": n}
        print(f"  r={r:.3f}, n={n}")

    # --- Verdict per family ---
    print("\n=== VERDICT ===")
    verdicts = {}
    for fam in families:
        real_r = voy_real[fam]["r"]
        null_mean = null_summary[fam]["mean"] if null_summary[fam] else None
        null_p95 = null_summary[fam]["p95"] if null_summary[fam] else None
        if real_r is None or null_mean is None:
            verdicts[fam] = "insufficient data"
            continue
        ratio = real_r / null_mean if null_mean > 0.01 else float("inf")
        exceeds_95 = real_r > null_p95
        if exceeds_95 and ratio >= 1.5:
            verdict = "supports productive morphology interpretation"
        elif ratio < 1.3:
            verdict = "artifact: correlation explained by Zipfian combinatorics (trigram null)"
        elif exceeds_95:
            verdict = "partial support: above null but weaker than expected for morphology"
        else:
            verdict = "not significantly above null 95th percentile"
        verdicts[fam] = {
            "real_r": real_r,
            "null_mean": null_mean,
            "null_p95": null_p95,
            "ratio_real_over_null": round(ratio, 2),
            "exceeds_null_p95": exceeds_95,
            "verdict": verdict,
        }
        print(f"  {fam}: real={real_r}, null_mean={null_mean}, null_p95={null_p95}, ratio={ratio:.2f}")
        print(f"        -> {verdict}")

    results["results"]["voynich_real"] = voy_real
    results["results"]["trigram_null"] = null_summary
    results["results"]["chaucer_natural"] = chaucer_r
    results["results"]["verdicts"] = verdicts

    out_path = os.path.join(PROJECT_ROOT, "results", "paradigm_null_results.json")
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nResults saved to {out_path}")


if __name__ == "__main__":
    main()
