#!/usr/bin/env python3
"""Create and optionally compile the self-contained Version 2 preprint bundle."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import tempfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VERSION = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
RELEASE_ROOT = ROOT / "release" / f"v{VERSION}"
SOURCE_ROOT = RELEASE_ROOT / "arxiv"
ZIP_PATH = RELEASE_ROOT / f"Voynich_Transition_Grammar_v{VERSION}_arxiv.zip"

SOURCE_FILES = {
    ROOT / "docs/main.tex": Path("main.tex"),
    ROOT / "docs/main.bbl": Path("main.bbl"),
    ROOT / "docs/references.bib": Path("references.bib"),
    ROOT / "docs/figures/prefix_suffix_v2.pdf": Path("figures/prefix_suffix_v2.pdf"),
}

README_TEXT = """Version 2 preprint source bundle

Paper: Boundary-Aware Token-Structure Analysis of the Voynich Manuscript:
A Reproducible Reassessment
Author: Amy Laird
Candidate: {version}

Compile with:
    latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex

main.bbl is included so the source can be compiled without running BibTeX.
references.bib is included for transparent bibliographic source. The single
figure is generated by the canonical repository pipeline.

This source reports corpus measurements. It makes no decipherment,
translation, language-identification, or natural-language-proof claim.
Canonical repository: https://github.com/amy2213/Voynich-Transition-Grammar
"""


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def copy_sources() -> None:
    SOURCE_ROOT.mkdir(parents=True, exist_ok=True)
    expected = {destination for destination in SOURCE_FILES.values()} | {Path("README.txt")}
    for existing in sorted(SOURCE_ROOT.rglob("*"), reverse=True):
        if existing.is_file() and existing.relative_to(SOURCE_ROOT) not in expected:
            existing.unlink()
    for source, destination in SOURCE_FILES.items():
        target = SOURCE_ROOT / destination
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
    (SOURCE_ROOT / "README.txt").write_text(
        README_TEXT.format(version=VERSION), encoding="utf-8"
    )


def create_deterministic_zip() -> None:
    ZIP_PATH.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(ZIP_PATH, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted(item for item in SOURCE_ROOT.rglob("*") if item.is_file()):
            relative = path.relative_to(SOURCE_ROOT).as_posix()
            info = zipfile.ZipInfo(relative, date_time=(2026, 7, 18, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, path.read_bytes(), compresslevel=9)


def independent_build() -> Path:
    with tempfile.TemporaryDirectory(prefix="voynich-preprint-") as temporary:
        build_root = Path(temporary)
        with zipfile.ZipFile(ZIP_PATH) as archive:
            archive.extractall(build_root)
        subprocess.run(
            ["latexmk", "-pdf", "-interaction=nonstopmode", "-halt-on-error", "main.tex"],
            cwd=build_root,
            check=True,
        )
        built_pdf = build_root / "main.pdf"
        target = RELEASE_ROOT / "paper.pdf"
        shutil.copyfile(built_pdf, target)
        shutil.copyfile(build_root / "main.log", RELEASE_ROOT / "build.log")
    return target


def write_evidence(built_pdf: Path | None) -> None:
    source_hashes = {
        path.relative_to(SOURCE_ROOT).as_posix(): sha256(path)
        for path in sorted(item for item in SOURCE_ROOT.rglob("*") if item.is_file())
    }
    build_log = RELEASE_ROOT / "build.log" if built_pdf else None
    build_log_text = build_log.read_text(encoding="utf-8", errors="replace") if build_log else ""
    manifest = {
        "schema_version": "1.0",
        "release_candidate": VERSION,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "source_directory": str(SOURCE_ROOT.relative_to(ROOT)),
        "source_sha256": source_hashes,
        "bundle": str(ZIP_PATH.relative_to(ROOT)),
        "bundle_sha256": sha256(ZIP_PATH),
        "independent_build_command": (
            "latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex"
        ),
        "independent_build_completed": built_pdf is not None,
        "paper": str(built_pdf.relative_to(ROOT)) if built_pdf else None,
        "paper_sha256": sha256(built_pdf) if built_pdf else None,
        "canonical_paper_sha256": sha256(ROOT / "docs/paper.pdf"),
        "build_log": str(build_log.relative_to(ROOT)) if build_log else None,
        "build_log_sha256": sha256(build_log) if build_log else None,
        "build_log_warning_count": build_log_text.count("Warning"),
        "build_log_undefined_reference_count": build_log_text.count("undefined"),
        "build_log_overfull_count": build_log_text.count("Overfull"),
    }
    manifest_path = RELEASE_ROOT / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    checksum_paths = [ZIP_PATH, ROOT / "docs/paper.pdf"]
    if built_pdf:
        checksum_paths.extend((built_pdf, RELEASE_ROOT / "build.log"))
    lines = [
        f"{sha256(path)}  {path.relative_to(ROOT).as_posix()}"
        for path in checksum_paths
    ]
    (RELEASE_ROOT / "SHA256SUMS").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--build", action="store_true", help="compile the extracted ZIP independently"
    )
    args = parser.parse_args()

    copy_sources()
    create_deterministic_zip()
    built_pdf = independent_build() if args.build else None
    write_evidence(built_pdf)
    print(f"Created {ZIP_PATH.relative_to(ROOT)}")
    if built_pdf:
        print(f"Built {built_pdf.relative_to(ROOT)} independently")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
